# ==========================================
# 🤲 libinput-gestures configuration
# ==========================================

# Swipe 3 fingers right to move to previous workspace
gesture swipe right 3 swaymsg workspace prev

# Swipe 3 fingers left to move to next workspace
gesture swipe left 3 swaymsg workspace next

# Swipe 3 fingers up to open Wofi (App Launcher)
gesture swipe up 3 swaymsg exec wofi --show drun

# Swipe 3 fingers down to close the active window
gesture swipe down 3 swaymsg kill
