pulse.properties = {
    ## Ensure pulse clients follow quantum limits
    pulse.min.quantum = 32/48000
}

stream.properties = {
    ## Set default properties for PulseAudio streams
    node.latency = 1024/48000
}
