---
- name: Dotfiles | Ensure data directories exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/{{ item }}"
    state: directory
    mode: '0755'
  loop: []

- name: Dotfiles | Check for existing .zshrc
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc_stat

- name: Dotfiles | Backup existing .zshrc if it is not a symlink
  ansible.builtin.command: mv "{{ ansible_env.HOME }}/.zshrc" "{{ ansible_env.HOME }}/.zshrc.bak"
  when: zshrc_stat.stat.exists and not zshrc_stat.stat.islnk

- name: Dotfiles | Check for existing sway config
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/sway/config"
  register: sway_stat

- name: Dotfiles | Check if sway directory is stowed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/sway"
  register: sway_dir_stat

- name: Dotfiles | Backup existing sway config if it is not stowed
  ansible.builtin.command: mv "{{ ansible_env.HOME }}/.config/sway/config" "{{ ansible_env.HOME }}/.config/sway/config.bak"
  when: 
    - sway_stat.stat.exists 
    - not sway_stat.stat.islnk
    - not (sway_dir_stat.stat.exists and sway_dir_stat.stat.islnk)

- name: Dotfiles | Ensure greetd directory exists
  ansible.builtin.file:
    path: /etc/greetd
    state: directory
    mode: '0755'
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Dotfiles | Deploy greetd configuration
  ansible.builtin.copy:
    src: "{{ dotfiles_dir }}/greetd/config.toml"
    dest: /etc/greetd/config.toml
    mode: '0644'
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Dotfiles | Stow packages
  ansible.builtin.command: stow -v -R -t "{{ ansible_env.HOME }}" -d "{{ dotfiles_dir }}" {{ item }}
  args:
    chdir: "{{ dotfiles_dir }}"
  loop: "{{ stow_packages }}"
  register: stow_res
  changed_when: >
    'LINK: ' in stow_res.stderr or
    'UNLINK: ' in stow_res.stderr or
    'MKDIR: ' in stow_res.stderr or
    'RMDIR: ' in stow_res.stderr
