---
- name: Dotfiles | Ensure data directories exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - lynx

- name: Dotfiles | Stow packages
  ansible.builtin.command: stow -v -R -t "{{ ansible_env.HOME }}" -d "{{ dotfiles_dir }}" {{ item }}
  args:
    chdir: "{{ dotfiles_dir }}"
  loop: "{{ stow_packages }}"
  register: stow_res
  changed_when: >
    'LINK: ' in stow_res.stderr or
    'UNLINK: ' in stow_res.stderr or
    'MKDIR: ' in stow_res.stderr or
    'RMDIR: ' in stow_res.stderr
