---
- name: Core | Install basic dependencies (macOS)
  community.general.homebrew:
    name:
      - curl
      - git
      - stow
      - zsh
      - fd
      - ripgrep
    state: present
    update_homebrew: true
  when: ansible_os_family == 'Darwin'

- name: Core | Ensure APT cache is updated
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: ansible_os_family == 'Debian'

- name: Core | Install basic dependencies (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - curl
      - git
      - stow
      - zsh
      - fd-find
      - ripgrep
      - build-essential
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Core | Ensure fd is symlinked on Debian/Ubuntu
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
  become: true
  when: ansible_os_family == 'Debian'

- name: Core | Install basic dependencies (Arch Linux)
  community.general.pacman:
    name:
      - curl
      - git
      - stow
      - zsh
      - fd
      - ripgrep
      - base-devel
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Core | Install basic dependencies (RedHat/Fedora)
  ansible.builtin.dnf:
    name:
      - curl
      - git
      - stow
      - zsh
      - fd-find
      - ripgrep
      - gcc
      - make
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == 'RedHat'
