format = "[$directory](bold cyan)$character"
add_newline = false

[username]
show_always = true
style_user = "bold white"

[hostname]
ssh_only = false
style = "bold white"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"
