context.properties = {
    ## Default clock rate
    default.clock.rate          = 48000
    ## Allowed clock rates for switching
    default.clock.allowed-rates = [ 44100 48000 88200 96000 ]
    
    ## Latency settings
    ## Lower quantum = lower latency, higher CPU usage
    default.clock.min-quantum   = 32
    default.clock.max-quantum   = 2048
    default.clock.quantum       = 1024
}
