# --- Font ---
font_family      JetBrains Mono Nerd Font
font_size        10.0
adjust_line_height 110%

# --- Giao diện ---
cursor_shape     beam
cursor_blink_interval 0.5
window_padding_width 10
# Độ trong suốt (0.8 - 0.9 là đẹp để vừa thấy hình nền vừa không bị rối)
background_opacity 0.95
#ide_window_decorations yes

# --- Màu sắc (Màu xám/đen của ThinkPad) ---
background #1a1a1a
foreground #dcdcdc

# --- Hiệu năng (Tận dụng Radeon Graphics) ---
repaint_delay    10
input_delay      3
sync_to_monitor  yes

# --- Phím tắt cơ bản (Giống phong cách Tiling) ---
map ctrl+shift+enter new_window
map ctrl+shift+l next_window
map ctrl+shift+h previous_window
